// <auto-generated/>
// This file auto generated by the Wintellect TFS 2010 Build Number Targets.
using System; 
using System.Reflection;
[assembly:AssemblyFileVersion("2.2.50831.65535")]
[assembly:AssemblyCompany("Cognizant")]
[assembly:AssemblyProduct("Paralegal")]
[assembly:AssemblyCopyright("Copyright © Cognizant Technology Solutions 2015")]
[assembly:AssemblyVersion("1.0.0.0")]
[assembly:AssemblyTitle("Built by 365180")]
