//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.UI.App.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CGN.Paralegal.UI.App.resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Needs To Create Control Set.
        /// </summary>
        public static string AdminNeedsToCreateControlSet {
            get {
                return ResourceManager.GetString("AdminNeedsToCreateControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Needs To Create QC Set.
        /// </summary>
        public static string AdminNeedsToCreateQCSet {
            get {
                return ResourceManager.GetString("AdminNeedsToCreateQCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Needs To Finalize Project.
        /// </summary>
        public static string AdminNeedsToFinalizeProject {
            get {
                return ResourceManager.GetString("AdminNeedsToFinalizeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Needs To Start Job.
        /// </summary>
        public static string AdminNeedsToStartJob {
            get {
                return ResourceManager.GetString("AdminNeedsToStartJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents.
        /// </summary>
        public static string AllDocuments {
            get {
                return ResourceManager.GetString("AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Job.
        /// </summary>
        public static string BatchJob {
            get {
                return ResourceManager.GetString("BatchJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Review.
        /// </summary>
        public static string ContinueReview {
            get {
                return ResourceManager.GetString("ContinueReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Documents.
        /// </summary>
        public static string ControlSetDocuments {
            get {
                return ResourceManager.GetString("ControlSetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Not Created.
        /// </summary>
        public static string ControlSetNotCreated {
            get {
                return ResourceManager.GetString("ControlSetNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Review.
        /// </summary>
        public static string ControlSetReview {
            get {
                return ResourceManager.GetString("ControlSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Control Set.
        /// </summary>
        public static string CreateControlSet {
            get {
                return ResourceManager.GetString("CreateControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QC Set.
        /// </summary>
        public static string CreateQCSet {
            get {
                return ResourceManager.GetString("CreateQCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Training Set.
        /// </summary>
        public static string CreateTrainingSet {
            get {
                return ResourceManager.GetString("CreateTrainingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs Coded.
        /// </summary>
        public static string DocsCoded {
            get {
                return ResourceManager.GetString("DocsCoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export table view documents is scheduled. You will be notified once job is completed.
        /// </summary>
        public static string ExportJobMessage {
            get {
                return ResourceManager.GetString("ExportJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize Project.
        /// </summary>
        public static string FinalizeProject {
            get {
                return ResourceManager.GetString("FinalizeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin of Error +/-.
        /// </summary>
        public static string MarginofError {
            get {
                return ResourceManager.GetString("MarginofError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Complete.
        /// </summary>
        public static string PercentComplete {
            get {
                return ResourceManager.GetString("PercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict.
        /// </summary>
        public static string Predict {
            get {
                return ResourceManager.GetString("Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict All.
        /// </summary>
        public static string PredictAll {
            get {
                return ResourceManager.GetString("PredictAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Set Documents.
        /// </summary>
        public static string PredictionSetDocuments {
            get {
                return ResourceManager.GetString("PredictionSetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Dashboard.
        /// </summary>
        public static string ProjectDashboard {
            get {
                return ResourceManager.GetString("ProjectDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Setup.
        /// </summary>
        public static string ProjectSetup {
            get {
                return ResourceManager.GetString("ProjectSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC.
        /// </summary>
        public static string QC {
            get {
                return ResourceManager.GetString("QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set Documents.
        /// </summary>
        public static string QCSetDocuments {
            get {
                return ResourceManager.GetString("QCSetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Set Not Created.
        /// </summary>
        public static string QCSetNotCreated {
            get {
                return ResourceManager.GetString("QCSetNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set Review.
        /// </summary>
        public static string QCSetReview {
            get {
                return ResourceManager.GetString("QCSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready To Start.
        /// </summary>
        public static string ReadyToStart {
            get {
                return ResourceManager.GetString("ReadyToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Control Set.
        /// </summary>
        public static string ReviewControlSet {
            get {
                return ResourceManager.GetString("ReviewControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review QC Set.
        /// </summary>
        public static string ReviewQCSet {
            get {
                return ResourceManager.GetString("ReviewQCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Training Set.
        /// </summary>
        public static string ReviewTrainingSet {
            get {
                return ResourceManager.GetString("ReviewTrainingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled / Running.
        /// </summary>
        public static string ScheduledRunning {
            get {
                return ResourceManager.GetString("ScheduledRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Project.
        /// </summary>
        public static string SetupProject {
            get {
                return ResourceManager.GetString("SetupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Review.
        /// </summary>
        public static string StartReview {
            get {
                return ResourceManager.GetString("StartReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical Confidence.
        /// </summary>
        public static string StatisticalConfidence {
            get {
                return ResourceManager.GetString("StatisticalConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items.
        /// </summary>
        public static string TotalItems {
            get {
                return ResourceManager.GetString("TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set.
        /// </summary>
        public static string TrainingSet {
            get {
                return ResourceManager.GetString("TrainingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set Documents.
        /// </summary>
        public static string TrainingSetDocuments {
            get {
                return ResourceManager.GetString("TrainingSetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set Review.
        /// </summary>
        public static string TrainingSetReview {
            get {
                return ResourceManager.GetString("TrainingSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train System.
        /// </summary>
        public static string TrainSystem {
            get {
                return ResourceManager.GetString("TrainSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Documents.
        /// </summary>
        public static string ViewDocuments {
            get {
                return ResourceManager.GetString("ViewDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Till Job Is Completed.
        /// </summary>
        public static string WaitTillJobCompleted {
            get {
                return ResourceManager.GetString("WaitTillJobCompleted", resourceCulture);
            }
        }
    }
}
