//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.UI.App.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Project {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Project() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CGN.Paralegal.UI.App.resources.Project", typeof(Project).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action 1.
        /// </summary>
        public static string Action1 {
            get {
                return ResourceManager.GetString("Action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action 2.
        /// </summary>
        public static string Action2 {
            get {
                return ResourceManager.GetString("Action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Documents to Project.
        /// </summary>
        public static string AddDocumentstoProject {
            get {
                return ResourceManager.GetString("AddDocumentstoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set section will be available after Reviewer has completed one training round..
        /// </summary>
        public static string AdminMessageAfterControlsetReview {
            get {
                return ResourceManager.GetString("AdminMessageAfterControlsetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Reviewer to start document review..
        /// </summary>
        public static string AdminMessageAfterCreateControlset {
            get {
                return ResourceManager.GetString("AdminMessageAfterCreateControlset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Job Complete. Create Verification Set and notify the Reviewer..
        /// </summary>
        public static string AdminMessageAfterPredictionComplete {
            get {
                return ResourceManager.GetString("AdminMessageAfterPredictionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to run predictions.
        /// </summary>
        public static string AdminMessageAfterTraining {
            get {
                return ResourceManager.GetString("AdminMessageAfterTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to send documents back to training or finish project..
        /// </summary>
        public static string AdminMessageAfterVerificationsetReview {
            get {
                return ResourceManager.GetString("AdminMessageAfterVerificationsetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Control Set to begin the process..
        /// </summary>
        public static string AdminMessageBeforeCreateControlset {
            get {
                return ResourceManager.GetString("AdminMessageBeforeCreateControlset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed all {1} documents in the verification set.
        /// </summary>
        public static string AdminVerificationStatusReviewCompleted {
            get {
                return ResourceManager.GetString("AdminVerificationStatusReviewCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed {1} of {2} documents in the verification set.
        /// </summary>
        public static string AdminVerificationStatusReviewInProgress {
            get {
                return ResourceManager.GetString("AdminVerificationStatusReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} documents to review in the verification set.
        /// </summary>
        public static string AdminVerificationStatusReviewNotStarted {
            get {
                return ResourceManager.GetString("AdminVerificationStatusReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dataset Documents.
        /// </summary>
        public static string AllDatasetDocuments {
            get {
                return ResourceManager.GetString("AllDatasetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents.
        /// </summary>
        public static string AllDocuments {
            get {
                return ResourceManager.GetString("AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} documents were reviewed.
        /// </summary>
        public static string AllDocumentsReviewed {
            get {
                return ResourceManager.GetString("AllDocumentsReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Training.
        /// </summary>
        public static string BackToTraining {
            get {
                return ResourceManager.GetString("BackToTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based On Current Round Training.
        /// </summary>
        public static string BasedOnCurrentRoundTraining {
            get {
                return ResourceManager.GetString("BasedOnCurrentRoundTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Relevant And Not Relevant.
        /// </summary>
        public static string BothRelevantAndNotRelevant {
            get {
                return ResourceManager.GetString("BothRelevantAndNotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Saved Search.
        /// </summary>
        public static string BySavedSearch {
            get {
                return ResourceManager.GetString("BySavedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Tag.
        /// </summary>
        public static string ByTag {
            get {
                return ResourceManager.GetString("ByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating.
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Workflow State.
        /// </summary>
        public static string ChangeWorkflowState {
            get {
                return ResourceManager.GetString("ChangeWorkflowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click Create to get started.
        /// </summary>
        public static string ClickCreateControlSet {
            get {
                return ResourceManager.GetString("ClickCreateControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding Summary.
        /// </summary>
        public static string CodingSummary {
            get {
                return ResourceManager.GetString("CodingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding Values.
        /// </summary>
        public static string CodingValues {
            get {
                return ResourceManager.GetString("CodingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        public static string Confidence {
            get {
                return ResourceManager.GetString("Confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence Level.
        /// </summary>
        public static string ConfidenceLevel {
            get {
                return ResourceManager.GetString("ConfidenceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confidence level.
        /// </summary>
        public static string ConfidenceLevelLowerCase {
            get {
                return ResourceManager.GetString("ConfidenceLevelLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Confidence.
        /// </summary>
        public static string ConfidenceValidationMessage {
            get {
                return ResourceManager.GetString("ConfidenceValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting Predict All will end training and move to next step. Are you sure you want to continue?.
        /// </summary>
        public static string ConfirmWorkflowChangeText {
            get {
                return ResourceManager.GetString("ConfirmWorkflowChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Review.
        /// </summary>
        public static string ContinueReview {
            get {
                return ResourceManager.GetString("ContinueReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set.
        /// </summary>
        public static string ControlSet {
            get {
                return ResourceManager.GetString("ControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Not Created.
        /// </summary>
        public static string ControlSetNotCreated {
            get {
                return ResourceManager.GetString("ControlSetNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set not Ready to Review.
        /// </summary>
        public static string ControlSetnotReadyReviewer {
            get {
                return ResourceManager.GetString("ControlSetnotReadyReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Not Started.
        /// </summary>
        public static string ControlSetNotStarted {
            get {
                return ResourceManager.GetString("ControlSetNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is  no Control Set for this project yet.
        /// </summary>
        public static string ControlSetNotStartedActionMessage {
            get {
                return ResourceManager.GetString("ControlSetNotStartedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Options.
        /// </summary>
        public static string ControlSetOptions {
            get {
                return ResourceManager.GetString("ControlSetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the confidence level and margin of error for your Control Set. The number of documents in the Control  Set varies dramatically based on which statistical options you select. .
        /// </summary>
        public static string ControlSetOptionsText {
            get {
                return ResourceManager.GetString("ControlSetOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Prevalence.
        /// </summary>
        public static string ControlSetPrevalence {
            get {
                return ResourceManager.GetString("ControlSetPrevalence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You coded {0}% of control set documents as relevant.
        /// </summary>
        public static string ControlSetPrevalenceMsg {
            get {
                return ResourceManager.GetString("ControlSetPrevalenceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Results.
        /// </summary>
        public static string ControlSetResults {
            get {
                return ResourceManager.GetString("ControlSetResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Review.
        /// </summary>
        public static string ControlSetReview {
            get {
                return ResourceManager.GetString("ControlSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set review is complete.
        /// </summary>
        public static string ControlSetReviewCompleted {
            get {
                return ResourceManager.GetString("ControlSetReviewCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed all {1} documents in the control set.
        /// </summary>
        public static string ControlSetReviewCompletedActionMessage {
            get {
                return ResourceManager.GetString("ControlSetReviewCompletedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed all {1} documents in the control set. Click Create Training Set to begin training.
        /// </summary>
        public static string ControlSetReviewCompletedNoTrainingActionMessage {
            get {
                return ResourceManager.GetString("ControlSetReviewCompletedNoTrainingActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed review of all {0} Control Set documents.
        /// </summary>
        public static string ControlSetReviewerCompletedActionMessage {
            get {
                return ResourceManager.GetString("ControlSetReviewerCompletedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed review of all {0} Control Set documents. Please wait for the admin to create a Training Set to continue.
        /// </summary>
        public static string ControlSetReviewerCompletedNoTrainingActionMessage {
            get {
                return ResourceManager.GetString("ControlSetReviewerCompletedNoTrainingActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reviewed {0} of {1} documents in the Control Set, click Continue to keep going.
        /// </summary>
        public static string ControlSetReviewerInProgressActionMessage {
            get {
                return ResourceManager.GetString("ControlSetReviewerInProgressActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0}  documents to review in the Control Set, click Start to begin reviewing.
        /// </summary>
        public static string ControlSetReviewerNotStartedActionMessage {
            get {
                return ResourceManager.GetString("ControlSetReviewerNotStartedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set review is in progress.
        /// </summary>
        public static string ControlSetReviewInProgress {
            get {
                return ResourceManager.GetString("ControlSetReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed {1} of {2} documents in the control set.
        /// </summary>
        public static string ControlSetReviewInProgressActionMessage {
            get {
                return ResourceManager.GetString("ControlSetReviewInProgressActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set review has not started.
        /// </summary>
        public static string ControlSetReviewNotStarted {
            get {
                return ResourceManager.GetString("ControlSetReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} documents to review in the control set.
        /// </summary>
        public static string ControlSetReviewNotStartedActionMessage {
            get {
                return ResourceManager.GetString("ControlSetReviewNotStartedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Summary.
        /// </summary>
        public static string ControlSetSummary {
            get {
                return ResourceManager.GetString("ControlSetSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Control Set.
        /// </summary>
        public static string CreateControlSet {
            get {
                return ResourceManager.GetString("CreateControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QC Set.
        /// </summary>
        public static string CreateQCSet {
            get {
                return ResourceManager.GetString("CreateQCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Training Set.
        /// </summary>
        public static string CreateTrainingSet {
            get {
                return ResourceManager.GetString("CreateTrainingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Verification Set.
        /// </summary>
        public static string CreateVerificationsSet {
            get {
                return ResourceManager.GetString("CreateVerificationsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Activity.
        /// </summary>
        public static string CurrentActivity {
            get {
                return ResourceManager.GetString("CurrentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current?.
        /// </summary>
        public static string CurrentQues {
            get {
                return ResourceManager.GetString("CurrentQues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Round.
        /// </summary>
        public static string CurrentRound {
            get {
                return ResourceManager.GetString("CurrentRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not available until review is complete.
        /// </summary>
        public static string DataNotAvailableUntilReview {
            get {
                return ResourceManager.GetString("DataNotAvailableUntilReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Project.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the project will remove all predictive coding fields related to the project..
        /// </summary>
        public static string DeleteProjectText1 {
            get {
                return ResourceManager.GetString("DeleteProjectText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the project the name below to verify you want to delete the project and then click Delete..
        /// </summary>
        public static string DeleteProjectText2 {
            get {
                return ResourceManager.GetString("DeleteProjectText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancies Statistics.
        /// </summary>
        public static string DiscrepancyStatistics {
            get {
                return ResourceManager.GetString("DiscrepancyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision is {0}% and Recall is {1}%.
        /// </summary>
        public static string DiscrepancyStatisticsMsg {
            get {
                return ResourceManager.GetString("DiscrepancyStatisticsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Estimates .
        /// </summary>
        public static string DocumentEstimates {
            get {
                return ResourceManager.GetString("DocumentEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents Coded.
        /// </summary>
        public static string DocumentsCoded {
            get {
                return ResourceManager.GetString("DocumentsCoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents Coding.
        /// </summary>
        public static string DocumentsCoding {
            get {
                return ResourceManager.GetString("DocumentsCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  document(s) found for.
        /// </summary>
        public static string DocumentsFoundFor {
            get {
                return ResourceManager.GetString("DocumentsFoundFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents in Set.
        /// </summary>
        public static string DocumentsInSet {
            get {
                return ResourceManager.GetString("DocumentsInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} documents need to be reviewed.
        /// </summary>
        public static string DocumentsNeedReview {
            get {
                return ResourceManager.GetString("DocumentsNeedReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to query.
        /// </summary>
        public static string EnterTextToQuery {
            get {
                return ResourceManager.GetString("EnterTextToQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name cannot contain special characters. Please update  Name..
        /// </summary>
        public static string ErrorNameInvalid {
            get {
                return ResourceManager.GetString("ErrorNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name cannot be longer than 40 characters. Please update Name..
        /// </summary>
        public static string ErrorNameMaxChars {
            get {
                return ResourceManager.GetString("ErrorNameMaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name cannot be left blank. Please populate..
        /// </summary>
        public static string ErrorNameRequired {
            get {
                return ResourceManager.GetString("ErrorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name cannot be duplicate within a dataset. Please update Name..
        /// </summary>
        public static string ErrorNameUnique {
            get {
                return ResourceManager.GetString("ErrorNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on add ControlSet:.
        /// </summary>
        public static string ErrorOnAddControlSet {
            get {
                return ResourceManager.GetString("ErrorOnAddControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on retrieving Sample Size:.
        /// </summary>
        public static string ErrorOnSampleSize {
            get {
                return ResourceManager.GetString("ErrorOnSampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all documents are categorized. Please run Predict All before being able to create a verification set..
        /// </summary>
        public static string ErrorPredictionNotCategorized {
            get {
                return ResourceManager.GetString("ErrorPredictionNotCategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project  Prefix cannot contain special characters. Please update Prefix..
        /// </summary>
        public static string ErrorPrefixInvalid {
            get {
                return ResourceManager.GetString("ErrorPrefixInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Field Prefix cannot be longer than 6 characters. Please update Name..
        /// </summary>
        public static string ErrorPrefixMaxChars {
            get {
                return ResourceManager.GetString("ErrorPrefixMaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Prefix cannot be left blank. Please populate..
        /// </summary>
        public static string ErrorPrefixRequired {
            get {
                return ResourceManager.GetString("ErrorPrefixRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Prefix cannot be duplicate within a dataset. Please update Prefix.
        /// </summary>
        public static string ErrorPrefixUnique {
            get {
                return ResourceManager.GetString("ErrorPrefixUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Relevance.
        /// </summary>
        public static string EstimatedRelevance {
            get {
                return ResourceManager.GetString("EstimatedRelevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Richness.
        /// </summary>
        public static string EstimatedRichness {
            get {
                return ResourceManager.GetString("EstimatedRichness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolution estimates that {0} of the total documents are relevant.
        /// </summary>
        public static string EstimatedRichnessMsg {
            get {
                return ResourceManager.GetString("EstimatedRichnessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        public static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Negatives.
        /// </summary>
        public static string FalseNegatives {
            get {
                return ResourceManager.GetString("FalseNegatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Control Set Test.
        /// </summary>
        public static string FinalControlSetTest {
            get {
                return ResourceManager.GetString("FinalControlSetTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize Project.
        /// </summary>
        public static string FinalizeProject {
            get {
                return ResourceManager.GetString("FinalizeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Verification Set Test.
        /// </summary>
        public static string FinalVerificationSetTest {
            get {
                return ResourceManager.GetString("FinalVerificationSetTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will display after first Training Round review has completed..
        /// </summary>
        public static string FirstRoundInProgress {
            get {
                return ResourceManager.GetString("FirstRoundInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Size.
        /// </summary>
        public static string FixedSize {
            get {
                return ResourceManager.GetString("FixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Docs.
        /// </summary>
        public static string HashDocs {
            get {
                return ResourceManager.GetString("HashDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select date and time greater than current date and time..
        /// </summary>
        public static string InvalidDateTime {
            get {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you entered does not match the current Predictive Coding Project name. Please enter the correct project name..
        /// </summary>
        public static string InvalidProjectName {
            get {
                return ResourceManager.GetString("InvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue .
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Options.
        /// </summary>
        public static string JobOptions {
            get {
                return ResourceManager.GetString("JobOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified Date.
        /// </summary>
        public static string LastModifiedDate {
            get {
                return ResourceManager.GetString("LastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Margin of Error.
        /// </summary>
        public static string MarginErrorValidationMessage {
            get {
                return ResourceManager.GetString("MarginErrorValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin of Error.
        /// </summary>
        public static string MarginOfError {
            get {
                return ResourceManager.GetString("MarginOfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin of error [Estimated].
        /// </summary>
        public static string MarginOfErrorEstimated {
            get {
                return ResourceManager.GetString("MarginOfErrorEstimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to margin of error.
        /// </summary>
        public static string MarginOfErrorLowerCase {
            get {
                return ResourceManager.GetString("MarginOfErrorLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter.
        /// </summary>
        public static string Matter {
            get {
                return ResourceManager.GetString("Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string Metric {
            get {
                return ResourceManager.GetString("Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Search.
        /// </summary>
        public static string NewSearch {
            get {
                return ResourceManager.GetString("NewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Activity.
        /// </summary>
        public static string NoActivity {
            get {
                return ResourceManager.GetString("NoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Control Set.
        /// </summary>
        public static string NoControlSet {
            get {
                return ResourceManager.GetString("NoControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Coded.
        /// </summary>
        public static string NotCoded {
            get {
                return ResourceManager.GetString("NotCoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Relevant.
        /// </summary>
        public static string NotRelevant {
            get {
                return ResourceManager.GetString("NotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of documents in Control Set.
        /// </summary>
        public static string NumberOfDocuments {
            get {
                return ResourceManager.GetString("NumberOfDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of documents in Verification Set.
        /// </summary>
        public static string NumberOfDocumentsInVerificationSet {
            get {
                return ResourceManager.GetString("NumberOfDocumentsInVerificationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Not Relevant.
        /// </summary>
        public static string OnlyNotRelevant {
            get {
                return ResourceManager.GetString("OnlyNotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Relevant.
        /// </summary>
        public static string OnlyRelevant {
            get {
                return ResourceManager.GetString("OnlyRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % False Negatives.
        /// </summary>
        public static string PercentFalseNegatives {
            get {
                return ResourceManager.GetString("PercentFalseNegatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of total population.
        /// </summary>
        public static string PercentTotalPopulation {
            get {
                return ResourceManager.GetString("PercentTotalPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict.
        /// </summary>
        public static string Predict {
            get {
                return ResourceManager.GetString("Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict Ahead.
        /// </summary>
        public static string PredictAhead {
            get {
                return ResourceManager.GetString("PredictAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict All.
        /// </summary>
        public static string PredictAll {
            get {
                return ResourceManager.GetString("PredictAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict All Documents.
        /// </summary>
        public static string PredictAllDocuments {
            get {
                return ResourceManager.GetString("PredictAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When do you want to start the Predict All job?.
        /// </summary>
        public static string PredictAllModalText {
            get {
                return ResourceManager.GetString("PredictAllModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will display after Predict All is completed..
        /// </summary>
        public static string PredictAllNotCompleted {
            get {
                return ResourceManager.GetString("PredictAllNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict All Summary.
        /// </summary>
        public static string PredictAllSummary {
            get {
                return ResourceManager.GetString("PredictAllSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict Control Set.
        /// </summary>
        public static string PredictControlset {
            get {
                return ResourceManager.GetString("PredictControlset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted.
        /// </summary>
        public static string Predicted {
            get {
                return ResourceManager.GetString("Predicted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed all {1} documents in training set {2}.  Click Create Verification Set to begin verification..
        /// </summary>
        public static string PredictionCompleteMessage {
            get {
                return ResourceManager.GetString("PredictionCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Discrepancies.
        /// </summary>
        public static string PredictionDiscrepancies {
            get {
                return ResourceManager.GetString("PredictionDiscrepancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed all {1} documents in training set {2}.  Predict all is currently running..
        /// </summary>
        public static string PredictionInprogressMessage {
            get {
                return ResourceManager.GetString("PredictionInprogressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Type.
        /// </summary>
        public static string PredictionType {
            get {
                return ResourceManager.GetString("PredictionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description.
        /// </summary>
        public static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string ProjectDetails {
            get {
                return ResourceManager.GetString("ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Documents.
        /// </summary>
        public static string ProjectDocuments {
            get {
                return ResourceManager.GetString("ProjectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Fields.
        /// </summary>
        public static string ProjectFields {
            get {
                return ResourceManager.GetString("ProjectFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project fields are automatically added to the dataset when a predictive coding project is created. A prefix makes it easy to identify the fields for this project..
        /// </summary>
        public static string ProjectFieldsText {
            get {
                return ResourceManager.GetString("ProjectFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Info.
        /// </summary>
        public static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Percentage.
        /// </summary>
        public static string ProjectPercentage {
            get {
                return ResourceManager.GetString("ProjectPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Setup.
        /// </summary>
        public static string ProjectSetup {
            get {
                return ResourceManager.GetString("ProjectSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name and Project Fields Prefix are required. They must be unique within a dataset..
        /// </summary>
        public static string ProjectSetupText {
            get {
                return ResourceManager.GetString("ProjectSetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC.
        /// </summary>
        public static string QC {
            get {
                return ResourceManager.GetString("QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Set.
        /// </summary>
        public static string QCSet {
            get {
                return ResourceManager.GetString("QCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Set attributes.
        /// </summary>
        public static string QCSetAttributes {
            get {
                return ResourceManager.GetString("QCSetAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  will display after QC set has been created.
        /// </summary>
        public static string QCSetHasBeenNotCreated {
            get {
                return ResourceManager.GetString("QCSetHasBeenNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must begin with an alphanumeric character[0-9,a-z,A-Z] and can contain space, underscore(_), period(.), comma (,), and dash(-), upto 20 characters maximum and minimum 2 characters..
        /// </summary>
        public static string QCSetNameInvalid {
            get {
                return ResourceManager.GetString("QCSetNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  will display after QC Set Review has created.
        /// </summary>
        public static string QCSetNotCreated {
            get {
                return ResourceManager.GetString("QCSetNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set Review.
        /// </summary>
        public static string QCSetReview {
            get {
                return ResourceManager.GetString("QCSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set review is complete.
        /// </summary>
        public static string QCSetReviewComplete {
            get {
                return ResourceManager.GetString("QCSetReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set review is in progress.
        /// </summary>
        public static string QCSetReviewInProgress {
            get {
                return ResourceManager.GetString("QCSetReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set review has not started.
        /// </summary>
        public static string QCSetReviewNotStarted {
            get {
                return ResourceManager.GetString("QCSetReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Sets Attributes.
        /// </summary>
        public static string QCSetsAttributes {
            get {
                return ResourceManager.GetString("QCSetsAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string QCSetSizeInvalidNumber {
            get {
                return ResourceManager.GetString("QCSetSizeInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number between 1 and .
        /// </summary>
        public static string QCSetSizeOutOfRange {
            get {
                return ResourceManager.GetString("QCSetSizeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control.
        /// </summary>
        public static string QualityControl {
            get {
                return ResourceManager.GetString("QualityControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall.
        /// </summary>
        public static string Recall {
            get {
                return ResourceManager.GetString("Recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant.
        /// </summary>
        public static string Relevant {
            get {
                return ResourceManager.GetString("Relevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant And Not Relevant.
        /// </summary>
        public static string RelevantNotRelevant {
            get {
                return ResourceManager.GetString("RelevantNotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Set (estimated).
        /// </summary>
        public static string ResultSetEstimated {
            get {
                return ResourceManager.GetString("ResultSetEstimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Set results are inconclusive..
        /// </summary>
        public static string ResultsInconclusive {
            get {
                return ResourceManager.GetString("ResultsInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Set results are outside Control Set tolerance..
        /// </summary>
        public static string ResultsOutsideTolerance {
            get {
                return ResourceManager.GetString("ResultsOutsideTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Set Estimate.
        /// </summary>
        public static string ResultsSetEstimate {
            get {
                return ResourceManager.GetString("ResultsSetEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Set results are within Control Set tolerance..
        /// </summary>
        public static string ResultsWithinTolerance {
            get {
                return ResourceManager.GetString("ResultsWithinTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Complete.
        /// </summary>
        public static string ReviewComplete {
            get {
                return ResourceManager.GetString("ReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Control Set.
        /// </summary>
        public static string ReviewControlSet {
            get {
                return ResourceManager.GetString("ReviewControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to begin Training Set..
        /// </summary>
        public static string ReviewerMessageAfterCreateControlset {
            get {
                return ResourceManager.GetString("ReviewerMessageAfterCreateControlset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents to review. An administrator must create a control set.
        /// </summary>
        public static string ReviewerMessaheBeforeCreateControlset {
            get {
                return ResourceManager.GetString("ReviewerMessaheBeforeCreateControlset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Administrator has finalized verification, training is complete.
        /// </summary>
        public static string ReviewerVerificationStatusReviewCompleted {
            get {
                return ResourceManager.GetString("ReviewerVerificationStatusReviewCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve reviewed {0} of {1} documents in the verification set, click Continue to keep going.
        /// </summary>
        public static string ReviewerVerificationStatusReviewInProgress {
            get {
                return ResourceManager.GetString("ReviewerVerificationStatusReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} documents to review in the verification set, click Start to begin reviewing.
        /// </summary>
        public static string ReviewerVerificationStatusReviewNotStarted {
            get {
                return ResourceManager.GetString("ReviewerVerificationStatusReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review In Progress.
        /// </summary>
        public static string ReviewInProgress {
            get {
                return ResourceManager.GetString("ReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Not Started.
        /// </summary>
        public static string ReviewNotStarted {
            get {
                return ResourceManager.GetString("ReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review QC Set.
        /// </summary>
        public static string ReviewQCSet {
            get {
                return ResourceManager.GetString("ReviewQCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Status.
        /// </summary>
        public static string ReviewStatus {
            get {
                return ResourceManager.GetString("ReviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Training Set.
        /// </summary>
        public static string ReviewTrainingSet {
            get {
                return ResourceManager.GetString("ReviewTrainingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richness.
        /// </summary>
        public static string Richness {
            get {
                return ResourceManager.GetString("Richness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds Completed.
        /// </summary>
        public static string RoundsCompleted {
            get {
                return ResourceManager.GetString("RoundsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Predictions.
        /// </summary>
        public static string RunPredictions {
            get {
                return ResourceManager.GetString("RunPredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Size.
        /// </summary>
        public static string SampleSize {
            get {
                return ResourceManager.GetString("SampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while calculating sample size..
        /// </summary>
        public static string SampleSizeError {
            get {
                return ResourceManager.GetString("SampleSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Method.
        /// </summary>
        public static string SamplingMethod {
            get {
                return ResourceManager.GetString("SamplingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Options.
        /// </summary>
        public static string SamplingOptions {
            get {
                return ResourceManager.GetString("SamplingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Query.
        /// </summary>
        public static string SavedQuery {
            get {
                return ResourceManager.GetString("SavedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Searches.
        /// </summary>
        public static string SavedSearches {
            get {
                return ResourceManager.GetString("SavedSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select One --.
        /// </summary>
        public static string SelectDefaultOption {
            get {
                return ResourceManager.GetString("SelectDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Documents.
        /// </summary>
        public static string SelectDocuments {
            get {
                return ResourceManager.GetString("SelectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which documents from dataset to include in the project..
        /// </summary>
        public static string SelectDocumentsText {
            get {
                return ResourceManager.GetString("SelectDocumentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Saved Search.
        /// </summary>
        public static string SelectSavedSearch {
            get {
                return ResourceManager.GetString("SelectSavedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tag.
        /// </summary>
        public static string SelectTag {
            get {
                return ResourceManager.GetString("SelectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Name.
        /// </summary>
        public static string SetName {
            get {
                return ResourceManager.GetString("SetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Project.
        /// </summary>
        public static string SetupProject {
            get {
                return ResourceManager.GetString("SetupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Review.
        /// </summary>
        public static string StartReview {
            get {
                return ResourceManager.GetString("StartReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical.
        /// </summary>
        public static string Statistical {
            get {
                return ResourceManager.GetString("Statistical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical Analysis.
        /// </summary>
        public static string StatisticalAnalysis {
            get {
                return ResourceManager.GetString("StatisticalAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical Confidence.
        /// </summary>
        public static string StatisticalConfidence {
            get {
                return ResourceManager.GetString("StatisticalConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical Options.
        /// </summary>
        public static string StatisticalOptions {
            get {
                return ResourceManager.GetString("StatisticalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical Sample.
        /// </summary>
        public static string StatisticalSample {
            get {
                return ResourceManager.GetString("StatisticalSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TotalCurrentRound {
            get {
                return ResourceManager.GetString("TotalCurrentRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Document Estimates .
        /// </summary>
        public static string TotalDocumentEstimates {
            get {
                return ResourceManager.GetString("TotalDocumentEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Documents.
        /// </summary>
        public static string TotalDocuments {
            get {
                return ResourceManager.GetString("TotalDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Not Relevant Documents.
        /// </summary>
        public static string TotalNotRelevant {
            get {
                return ResourceManager.GetString("TotalNotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Project Documents.
        /// </summary>
        public static string TotalProjectDocuments {
            get {
                return ResourceManager.GetString("TotalProjectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Relevant Documents.
        /// </summary>
        public static string TotalRelevant {
            get {
                return ResourceManager.GetString("TotalRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rounds Completed.
        /// </summary>
        public static string TotalRoundsCompleted {
            get {
                return ResourceManager.GetString("TotalRoundsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Skipped Documents.
        /// </summary>
        public static string TotalSkipped {
            get {
                return ResourceManager.GetString("TotalSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set {0} Complete, Learning has Stabilized.
        /// </summary>
        public static string TrainingComplete {
            get {
                return ResourceManager.GetString("TrainingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed all {1} documents in training set {2}, and system learning has stabilized.
        /// </summary>
        public static string TrainingCompleteMessage {
            get {
                return ResourceManager.GetString("TrainingCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Complete.
        /// </summary>
        public static string TrainingCompleteReviewer {
            get {
                return ResourceManager.GetString("TrainingCompleteReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has finalized the training phase after training set {0}.
        /// </summary>
        public static string TrainingCompleteReviewerActionMessage {
            get {
                return ResourceManager.GetString("TrainingCompleteReviewerActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed all {1} documents in training set {2}, and system learning has stabilized. Click Run Predictions to continue.
        /// </summary>
        public static string TrainingCompleteRunPredictionsMessage {
            get {
                return ResourceManager.GetString("TrainingCompleteRunPredictionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Not Started.
        /// </summary>
        public static string TrainingNotStarted {
            get {
                return ResourceManager.GetString("TrainingNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Results.
        /// </summary>
        public static string TrainingResults {
            get {
                return ResourceManager.GetString("TrainingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Round.
        /// </summary>
        public static string TrainingRound {
            get {
                return ResourceManager.GetString("TrainingRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set.
        /// </summary>
        public static string TrainingSet {
            get {
                return ResourceManager.GetString("TrainingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set Progress.
        /// </summary>
        public static string TrainingSetProgress {
            get {
                return ResourceManager.GetString("TrainingSetProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set review is Complete.
        /// </summary>
        public static string TrainingSetReviewComplete {
            get {
                return ResourceManager.GetString("TrainingSetReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reviewed {0} out of {1} documents in training set {2}, click Continue to keep going.
        /// </summary>
        public static string TrainingSetReviewerInProgressActionMessage {
            get {
                return ResourceManager.GetString("TrainingSetReviewerInProgressActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} documents to review in training set {1}, click Start to begin reviewing.
        /// </summary>
        public static string TrainingSetReviewerNotStartedActionMessage {
            get {
                return ResourceManager.GetString("TrainingSetReviewerNotStartedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set review is in progress.
        /// </summary>
        public static string TrainingSetReviewInProgress {
            get {
                return ResourceManager.GetString("TrainingSetReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviewed {1} of {2} documents in training set {3}.
        /// </summary>
        public static string TrainingSetReviewInProgressActionMessage {
            get {
                return ResourceManager.GetString("TrainingSetReviewInProgressActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set {0}  Review in Progress.
        /// </summary>
        public static string TrainingSetReviewInProgressWithName {
            get {
                return ResourceManager.GetString("TrainingSetReviewInProgressWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set review has not started.
        /// </summary>
        public static string TrainingSetReviewNotStarted {
            get {
                return ResourceManager.GetString("TrainingSetReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} documents to review in training set {2}.
        /// </summary>
        public static string TrainingSetReviewNotStartedActionMessage {
            get {
                return ResourceManager.GetString("TrainingSetReviewNotStartedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set {0} Review not Started.
        /// </summary>
        public static string TrainingSetReviewNotStartedWithName {
            get {
                return ResourceManager.GetString("TrainingSetReviewNotStartedWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Summary.
        /// </summary>
        public static string TrainingSummary {
            get {
                return ResourceManager.GetString("TrainingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Totals.
        /// </summary>
        public static string TrainingTotals {
            get {
                return ResourceManager.GetString("TrainingTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Trend.
        /// </summary>
        public static string TrainingTrend {
            get {
                return ResourceManager.GetString("TrainingTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train System.
        /// </summary>
        public static string TrainSystem {
            get {
                return ResourceManager.GetString("TrainSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized Set [Estimated].
        /// </summary>
        public static string UncategorizedSetEstimated {
            get {
                return ResourceManager.GetString("UncategorizedSetEstimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification testing showed a {0}% decrease in F1 value to {1}%, with false negatives at {2}%.
        /// </summary>
        public static string VerificationF1Decrease {
            get {
                return ResourceManager.GetString("VerificationF1Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification testing showed a {0}% increase in F1 value to {1}%, with false negatives at {2}%.
        /// </summary>
        public static string VerificationF1Increase {
            get {
                return ResourceManager.GetString("VerificationF1Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification testing showed F1 stable at {0}%, with false negatives at {1}%.
        /// </summary>
        public static string VerificationF1Stable {
            get {
                return ResourceManager.GetString("VerificationF1Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set.
        /// </summary>
        public static string VerificationSet {
            get {
                return ResourceManager.GetString("VerificationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set Name.
        /// </summary>
        public static string VerificationSetName {
            get {
                return ResourceManager.GetString("VerificationSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set Options.
        /// </summary>
        public static string VerificationSetOptions {
            get {
                return ResourceManager.GetString("VerificationSetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the options for your Verification Set..
        /// </summary>
        public static string VerificationSetOptionsText {
            get {
                return ResourceManager.GetString("VerificationSetOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of system predictions do you want to include in this Verification Set?.
        /// </summary>
        public static string VerificationSetTypeText {
            get {
                return ResourceManager.GetString("VerificationSetTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Test Results.
        /// </summary>
        public static string VerificationTestResults {
            get {
                return ResourceManager.GetString("VerificationTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all documents.
        /// </summary>
        public static string ViewAllDocuments {
            get {
                return ResourceManager.GetString("ViewAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Verification Set Details.
        /// </summary>
        public static string ViewVerificationDetails {
            get {
                return ResourceManager.GetString("ViewVerificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
