//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.UI.App.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reviewer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reviewer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CGN.Paralegal.UI.App.resources.Reviewer", typeof(Reviewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Needs to Start Job.
        /// </summary>
        public static string AdminNeedsToStartJob {
            get {
                return ResourceManager.GetString("AdminNeedsToStartJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents.
        /// </summary>
        public static string AllDocumentsReview {
            get {
                return ResourceManager.GetString("AllDocumentsReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto advance.
        /// </summary>
        public static string AutoAdvance {
            get {
                return ResourceManager.GetString("AutoAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Training.
        /// </summary>
        public static string ContinueTraining {
            get {
                return ResourceManager.GetString("ContinueTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Training Set Review.
        /// </summary>
        public static string ContinueTrainingSetReview {
            get {
                return ResourceManager.GetString("ContinueTrainingSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Training round did not contain at least one designation for Relevant and Not Relevant. More documents will be added to the training round..
        /// </summary>
        public static string ContinueTrainingText {
            get {
                return ResourceManager.GetString("ContinueTrainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Review.
        /// </summary>
        public static string ControlSetReview {
            get {
                return ResourceManager.GetString("ControlSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Review Complete.
        /// </summary>
        public static string ControlSetReviewComplete {
            get {
                return ResourceManager.GetString("ControlSetReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Control #.
        /// </summary>
        public static string DocumentControlNumber {
            get {
                return ResourceManager.GetString("DocumentControlNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Path.
        /// </summary>
        public static string DocumentPath {
            get {
                return ResourceManager.GetString("DocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documents.
        /// </summary>
        public static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered.
        /// </summary>
        public static string Filtered {
            get {
                return ResourceManager.GetString("Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize Project.
        /// </summary>
        public static string FinalizeProject {
            get {
                return ResourceManager.GetString("FinalizeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed coding all the Control Set documents..
        /// </summary>
        public static string FinishControlText1 {
            get {
                return ResourceManager.GetString("FinishControlText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to return to your project dashboard to see the results of the review, and to launch the next phase of training the system.
        /// </summary>
        public static string FinishControlText2 {
            get {
                return ResourceManager.GetString("FinishControlText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Verification Set Review.
        /// </summary>
        public static string FinishQCSetReview {
            get {
                return ResourceManager.GetString("FinishQCSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed coding all the Verification Set documents..
        /// </summary>
        public static string FinishQCText1 {
            get {
                return ResourceManager.GetString("FinishQCText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed coding all the current training set.
        /// </summary>
        public static string FinishTrainingRoundText1 {
            get {
                return ResourceManager.GetString("FinishTrainingRoundText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Training Set Review.
        /// </summary>
        public static string FinishTrainingSetReview {
            get {
                return ResourceManager.GetString("FinishTrainingSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed coding all the Training Set documents..
        /// </summary>
        public static string FinishTrainingSetText1 {
            get {
                return ResourceManager.GetString("FinishTrainingSetText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do next?.
        /// </summary>
        public static string NextStepText {
            get {
                return ResourceManager.GetString("NextStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Relevant.
        /// </summary>
        public static string NotRelevant {
            get {
                return ResourceManager.GetString("NotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict All.
        /// </summary>
        public static string PredictAll {
            get {
                return ResourceManager.GetString("PredictAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Set Review.
        /// </summary>
        public static string PredictionSetReview {
            get {
                return ResourceManager.GetString("PredictionSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Dashboard.
        /// </summary>
        public static string ProjectDashboard {
            get {
                return ResourceManager.GetString("ProjectDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set Review.
        /// </summary>
        public static string QCSetReview {
            get {
                return ResourceManager.GetString("QCSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set Review Complete.
        /// </summary>
        public static string QCSetReviewComplete {
            get {
                return ResourceManager.GetString("QCSetReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant.
        /// </summary>
        public static string Relevant {
            get {
                return ResourceManager.GetString("Relevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipDocument {
            get {
                return ResourceManager.GetString("SkipDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Training.
        /// </summary>
        public static string StartTraining {
            get {
                return ResourceManager.GetString("StartTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Training Review.
        /// </summary>
        public static string StartTrainingReview {
            get {
                return ResourceManager.GetString("StartTrainingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Next Training Set.
        /// </summary>
        public static string StartTrainingSetRound {
            get {
                return ResourceManager.GetString("StartTrainingSetRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set Review.
        /// </summary>
        public static string TrainingSetReview {
            get {
                return ResourceManager.GetString("TrainingSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set Review Complete.
        /// </summary>
        public static string TrainingSetReviewComplete {
            get {
                return ResourceManager.GetString("TrainingSetReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Round Review Complete.
        /// </summary>
        public static string TrainingSetRoundReviewComplete {
            get {
                return ResourceManager.GetString("TrainingSetRoundReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Set.
        /// </summary>
        public static string ViewSet {
            get {
                return ResourceManager.GetString("ViewSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
