//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.UI.App.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Review {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Review() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CGN.Paralegal.UI.App.resources.Review", typeof(Review).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Docs.
        /// </summary>
        public static string AllDocs {
            get {
                return ResourceManager.GetString("AllDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assisted Review.
        /// </summary>
        public static string AssistedReview {
            get {
                return ResourceManager.GetString("AssistedReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachmt.
        /// </summary>
        public static string Attachmt {
            get {
                return ResourceManager.GetString("Attachmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on.
        /// </summary>
        public static string BasedOn {
            get {
                return ResourceManager.GetString("BasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batesmsg.
        /// </summary>
        public static string Batesmsg {
            get {
                return ResourceManager.GetString("Batesmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding Progress.
        /// </summary>
        public static string CodingProgress {
            get {
                return ResourceManager.GetString("CodingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Review.
        /// </summary>
        public static string ContinueReview {
            get {
                return ResourceManager.GetString("ContinueReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control #.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set.
        /// </summary>
        public static string ControlSet {
            get {
                return ResourceManager.GetString("ControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Documents.
        /// </summary>
        public static string ControlSetDocuments {
            get {
                return ResourceManager.GetString("ControlSetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Not Created.
        /// </summary>
        public static string ControlSetNotCreated {
            get {
                return ResourceManager.GetString("ControlSetNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Review.
        /// </summary>
        public static string ControlSetReview {
            get {
                return ResourceManager.GetString("ControlSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Review Completed.
        /// </summary>
        public static string ControlSetReviewCompleted {
            get {
                return ResourceManager.GetString("ControlSetReviewCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Review In Progress.
        /// </summary>
        public static string ControlSetReviewInProgress {
            get {
                return ResourceManager.GetString("ControlSetReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Set Review Not Started.
        /// </summary>
        public static string ControlSetReviewNotStarted {
            get {
                return ResourceManager.GetString("ControlSetReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current?.
        /// </summary>
        public static string CurrentQues {
            get {
                return ResourceManager.GetString("CurrentQues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Round.
        /// </summary>
        public static string CurrentRound {
            get {
                return ResourceManager.GetString("CurrentRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCN.
        /// </summary>
        public static string DCN {
            get {
                return ResourceManager.GetString("DCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocId.
        /// </summary>
        public static string DocId {
            get {
                return ResourceManager.GetString("DocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents Coding.
        /// </summary>
        public static string DocumentsCoding {
            get {
                return ResourceManager.GetString("DocumentsCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents In Set.
        /// </summary>
        public static string DocumentsInSet {
            get {
                return ResourceManager.GetString("DocumentsInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDFolder.
        /// </summary>
        public static string EDFolder {
            get {
                return ResourceManager.GetString("EDFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Relevant.
        /// </summary>
        public static string EstimatedRelevant {
            get {
                return ResourceManager.GetString("EstimatedRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpt.
        /// </summary>
        public static string Excerpt {
            get {
                return ResourceManager.GetString("Excerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpts.
        /// </summary>
        public static string Excerpts {
            get {
                return ResourceManager.GetString("Excerpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Docs.
        /// </summary>
        public static string HashDocs {
            get {
                return ResourceManager.GetString("HashDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid numeric value..
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Relevant.
        /// </summary>
        public static string NonRelevant {
            get {
                return ResourceManager.GetString("NonRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Coded.
        /// </summary>
        public static string NotCoded {
            get {
                return ResourceManager.GetString("NotCoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Relevant.
        /// </summary>
        public static string NotRelevant {
            get {
                return ResourceManager.GetString("NotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between 1 and.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentId.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % richness.
        /// </summary>
        public static string PercentRichness {
            get {
                return ResourceManager.GetString("PercentRichness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict All.
        /// </summary>
        public static string PredictAll {
            get {
                return ResourceManager.GetString("PredictAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict All And Final Review.
        /// </summary>
        public static string PredictAllAndFinalReview {
            get {
                return ResourceManager.GetString("PredictAllAndFinalReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Documents.
        /// </summary>
        public static string ProjectDocuments {
            get {
                return ResourceManager.GetString("ProjectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Setup.
        /// </summary>
        public static string ProjectSetup {
            get {
                return ResourceManager.GetString("ProjectSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Set.
        /// </summary>
        public static string QCSet {
            get {
                return ResourceManager.GetString("QCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set Review.
        /// </summary>
        public static string QCSetReview {
            get {
                return ResourceManager.GetString("QCSetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control Set.
        /// </summary>
        public static string QualityControlSet {
            get {
                return ResourceManager.GetString("QualityControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        public static string Relevance {
            get {
                return ResourceManager.GetString("Relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant.
        /// </summary>
        public static string Relevant {
            get {
                return ResourceManager.GetString("Relevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Complete.
        /// </summary>
        public static string ReviewComplete {
            get {
                return ResourceManager.GetString("ReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to begin Training Set..
        /// </summary>
        public static string ReviewerMessageAfterCreateControlset {
            get {
                return ResourceManager.GetString("ReviewerMessageAfterCreateControlset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review In Progress.
        /// </summary>
        public static string ReviewInProgress {
            get {
                return ResourceManager.GetString("ReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Not Started.
        /// </summary>
        public static string ReviewNotStarted {
            get {
                return ResourceManager.GetString("ReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Status.
        /// </summary>
        public static string ReviewStatus {
            get {
                return ResourceManager.GetString("ReviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rounds Completed.
        /// </summary>
        public static string RoundsCompleted {
            get {
                return ResourceManager.GetString("RoundsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string shorttext {
            get {
                return ResourceManager.GetString("shorttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Review.
        /// </summary>
        public static string StartReview {
            get {
                return ResourceManager.GetString("StartReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadId.
        /// </summary>
        public static string ThreadId {
            get {
                return ResourceManager.GetString("ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TotalCurrentRound {
            get {
                return ResourceManager.GetString("TotalCurrentRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Document Estimates .
        /// </summary>
        public static string TotalDocumentEstimates {
            get {
                return ResourceManager.GetString("TotalDocumentEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Documents.
        /// </summary>
        public static string TotalDocuments {
            get {
                return ResourceManager.GetString("TotalDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Not Relevant Documents.
        /// </summary>
        public static string TotalNotRelevant {
            get {
                return ResourceManager.GetString("TotalNotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Project Documents.
        /// </summary>
        public static string TotalProjectDocuments {
            get {
                return ResourceManager.GetString("TotalProjectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Relevant Documents.
        /// </summary>
        public static string TotalRelevant {
            get {
                return ResourceManager.GetString("TotalRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Skipped Documents.
        /// </summary>
        public static string TotalSkipped {
            get {
                return ResourceManager.GetString("TotalSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set.
        /// </summary>
        public static string TrainingSet {
            get {
                return ResourceManager.GetString("TrainingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Set Progress.
        /// </summary>
        public static string TrainingSetProgress {
            get {
                return ResourceManager.GetString("TrainingSetProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Summary.
        /// </summary>
        public static string TrainingSummary {
            get {
                return ResourceManager.GetString("TrainingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Totals.
        /// </summary>
        public static string TrainingTotals {
            get {
                return ResourceManager.GetString("TrainingTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train System.
        /// </summary>
        public static string TrainSystem {
            get {
                return ResourceManager.GetString("TrainSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Set.
        /// </summary>
        public static string VerificationSet {
            get {
                return ResourceManager.GetString("VerificationSet", resourceCulture);
            }
        }
    }
}
