//IMPORTANT: This is a sample js file for localization strings
// This file should be created dynamically from resx file(s).
// DO NOT USE a static file this in production!
var ProjectWizardResources = {
    ProjectSettings: 'Project Settings',
    Name: 'Name',
    Description: 'Description',
    DocSourceOptions: 'Document Source Options',
    Prev: 'Prev',
    Next: 'Next',
    Finish: 'Finish',
    NameRequired: 'Name is required',
    NameInvalid: 'Name is invalid (should have atleast one alphabet[a-z][A-Z] or number[0-9] between 2-200 characters)',
    DescriptionInvalid: 'Description is invalid',
    SampleCustomValidatorMessage: 'Description cannot be 1',
    ValidationErrors: 'Please correct the errors below:',
    NoWhiteSpaceValidation:"No whitespace",
    NumericValidation :"Atleast one numeric character",
    LowercaseValidation:"Atleast one lowercase character",
    UppercaseValidation: "Atleast one uppercase character",
    SpecialValidation: "Atleast one special character",
    AllDocs: 'All Docs',
    Tag: 'Tag',
    SavedSearch: 'Saved Search',
    IdentifyRepeatedContent: 'Identify Repeated Content',
    Confidence: 'Confidence',
    MarginOfError: 'Margin of Error',
    StratifyByCustodian: 'Stratify by Custodian',
    CustodianField: 'Custodian Field',
    SampleSize: 'Sample Size',
    Calculate: 'Calculate',
    ExampleSetOptions: 'Example Set Options',
    Recommended: 'Recommended',
    PreCoded: 'Pre-Coded',
    LimitExamples: 'Limit # of Examples',
    NumExamples: '# of Examples',
    SampleCustomValidator: 'Margin of Error must be greater than 2%',
    Summary:"Summary",
    ProjectName:"Project Name",
    Source:"Source",
    TotalDocuments:"Total Documents",
    DocumentTextField : "Document Text Field",
    DocumentText : "Document Text",
    CrossReferenceField:"Cross Reference Field",
    DCN : "DCN",
    CustodianField : "Custodian Field",
    ControlSet : "Control Set",
    PercentConfidence : "% Confidence",
    PercentMarginOfError : "% Margin of Error",
    TrainingSet : "Training Set"
};