//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.UI.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Project {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Project() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CGN.Paralegal.UI.Tests.Resources.Project", typeof(Project).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coded.
        /// </summary>
        internal static string Coded {
            get {
                return ResourceManager.GetString("Coded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string NotCodedCount {
            get {
                return ResourceManager.GetString("NotCodedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not_Relevant.
        /// </summary>
        internal static string NotRelevant {
            get {
                return ResourceManager.GetString("NotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string NotRelevantCount {
            get {
                return ResourceManager.GetString("NotRelevantCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Project Description.
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Project.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCP.
        /// </summary>
        internal static string ProjectPrefix {
            get {
                return ResourceManager.GetString("ProjectPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant.
        /// </summary>
        internal static string Relevant {
            get {
                return ResourceManager.GetString("Relevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string RelevantCount {
            get {
                return ResourceManager.GetString("RelevantCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Complete.
        /// </summary>
        internal static string ReviewComplete {
            get {
                return ResourceManager.GetString("ReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review in Progress.
        /// </summary>
        internal static string ReviewInProgress {
            get {
                return ResourceManager.GetString("ReviewInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review not Started.
        /// </summary>
        internal static string ReviewNotStarted {
            get {
                return ResourceManager.GetString("ReviewNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brain.
        /// </summary>
        internal static string SearchQuery {
            get {
                return ResourceManager.GetString("SearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START REVIEW.
        /// </summary>
        internal static string StartReview {
            get {
                return ResourceManager.GetString("StartReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string TotalDocumentCount {
            get {
                return ResourceManager.GetString("TotalDocumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string TotalDocumentCountAfterAddDocuments {
            get {
                return ResourceManager.GetString("TotalDocumentCountAfterAddDocuments", resourceCulture);
            }
        }
    }
}
