//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_of_Law
    {
        public Area_of_Law()
        {
            this.Case_Area_of_law = new HashSet<Case_Area_of_law>();
            this.Para_Legal_Law_Area = new HashSet<Para_Legal_Law_Area>();
        }
    
        public int Law_id { get; set; }
        public string Law_name { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    
        public virtual ICollection<Case_Area_of_law> Case_Area_of_law { get; set; }
        public virtual ICollection<Para_Legal_Law_Area> Para_Legal_Law_Area { get; set; }
    }
}
