//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_Area_of_law
    {
        public int Case_area_of_law_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> law_id { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    
        public virtual Area_of_Law Area_of_Law { get; set; }
        public virtual Case Case { get; set; }
    }
}
