//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law_firm
    {
        public Law_firm()
        {
            this.Law_firm_para_legal = new HashSet<Law_firm_para_legal>();
        }
    
        public int Law_firm_id { get; set; }
        public string Type { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    
        public virtual ICollection<Law_firm_para_legal> Law_firm_para_legal { get; set; }
    }
}
