//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law_firm_para_legal
    {
        public int Law_firm_para_legal_id { get; set; }
        public Nullable<int> Law_firm_id { get; set; }
        public Nullable<int> Para_legal_id { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    
        public virtual Law_firm Law_firm { get; set; }
        public virtual Para_legal Para_legal { get; set; }
    }
}
