//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Case_location = new HashSet<Case_location>();
            this.Para_Legal_Location = new HashSet<Para_Legal_Location>();
        }
    
        public int Location_id { get; set; }
        public string Location_name { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    
        public virtual ICollection<Case_location> Case_location { get; set; }
        public virtual ICollection<Para_Legal_Location> Para_Legal_Location { get; set; }
    }
}
