//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Para_legal
    {
        public Para_legal()
        {
            this.Law_firm_para_legal = new HashSet<Law_firm_para_legal>();
            this.Para_Legal_Law_Area = new HashSet<Para_Legal_Law_Area>();
            this.Para_Legal_Contact = new HashSet<Para_Legal_Contact>();
            this.Para_legal_cases = new HashSet<Para_legal_cases>();
            this.Para_Legal_Location = new HashSet<Para_Legal_Location>();
            this.Paralegal_Comment = new HashSet<Paralegal_Comment>();
        }
    
        public int Para_legal_id { get; set; }
        public string Para_legal_name { get; set; }
        public string Short_desc { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    
        public virtual ICollection<Law_firm_para_legal> Law_firm_para_legal { get; set; }
        public virtual ICollection<Para_Legal_Law_Area> Para_Legal_Law_Area { get; set; }
        public virtual ICollection<Para_Legal_Contact> Para_Legal_Contact { get; set; }
        public virtual ICollection<Para_legal_cases> Para_legal_cases { get; set; }
        public virtual ICollection<Para_Legal_Location> Para_Legal_Location { get; set; }
        public virtual ICollection<Paralegal_Comment> Paralegal_Comment { get; set; }
    }
}
