//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLByCity
    {
        public int Para_legal_id { get; set; }
        public string Para_legal_name { get; set; }
        public string Short_desc { get; set; }
        public string Location_name { get; set; }
    }
}
