//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLMasterEntities : DbContext
    {
        public PLMasterEntities()
            : base("name=PLMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Area_of_Law> Area_of_Law { get; set; }
        public virtual DbSet<Case_Area_of_law> Case_Area_of_law { get; set; }
        public virtual DbSet<Case_location> Case_location { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Law_firm> Law_firm { get; set; }
        public virtual DbSet<Law_firm_para_legal> Law_firm_para_legal { get; set; }
        public virtual DbSet<Legal_information> Legal_information { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Para_legal> Para_legal { get; set; }
        public virtual DbSet<Para_legal_cases> Para_legal_cases { get; set; }
        public virtual DbSet<Para_Legal_Contact> Para_Legal_Contact { get; set; }
        public virtual DbSet<Para_Legal_Law_Area> Para_Legal_Law_Area { get; set; }
        public virtual DbSet<Para_Legal_Location> Para_Legal_Location { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<PLByAOP> PLByAOPs { get; set; }
        public virtual DbSet<PLByCity> PLByCities { get; set; }
        public virtual DbSet<Paralegal_Comment> Paralegal_Comment { get; set; }
    }
}
