//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGN.Paralegal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Question_id { get; set; }
        public string Question1 { get; set; }
        public Nullable<int> Legal_information_id { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string Last_Updated_by { get; set; }
        public Nullable<System.DateTime> Last_Updated_at { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Legal_information Legal_information { get; set; }
    }
}
